// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-Vh6_0uNwEnsveeekL1O6DquQaFpOco',
    appId: '1:879318355876:web:573f029fe8e51787e6bb31',
    messagingSenderId: '879318355876',
    projectId: 'viax-81a5e',
    authDomain: 'viax-81a5e.firebaseapp.com',
    storageBucket: 'viax-81a5e.firebasestorage.app',
    measurementId: 'G-M5TH2MGMFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcit9gkhhtM2aUv2DNlh938Qxl0jwL50E',
    appId: '1:879318355876:android:df6e77f75ed055f5e6bb31',
    messagingSenderId: '879318355876',
    projectId: 'viax-81a5e',
    storageBucket: 'viax-81a5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5VuUR1fNtcuWzp3bS0MA89H7tVkDXbi4',
    appId: '1:879318355876:ios:e44272cee9c3af2ee6bb31',
    messagingSenderId: '879318355876',
    projectId: 'viax-81a5e',
    storageBucket: 'viax-81a5e.firebasestorage.app',
    iosBundleId: 'com.example.pingGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5VuUR1fNtcuWzp3bS0MA89H7tVkDXbi4',
    appId: '1:879318355876:ios:6aee6b2994c5555ae6bb31',
    messagingSenderId: '879318355876',
    projectId: 'viax-81a5e',
    storageBucket: 'viax-81a5e.firebasestorage.app',
    iosBundleId: 'com.example.viax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ-Vh6_0uNwEnsveeekL1O6DquQaFpOco',
    appId: '1:879318355876:web:eddc3757bc7dcb10e6bb31',
    messagingSenderId: '879318355876',
    projectId: 'viax-81a5e',
    authDomain: 'viax-81a5e.firebaseapp.com',
    storageBucket: 'viax-81a5e.firebasestorage.app',
    measurementId: 'G-XV85F958QT',
  );
}