[program:viax_pricing_service]
command=docker compose -f /var/www/viax/services/pricing/docker-compose.yml up --no-log-prefix
directory=/var/www/viax/services/pricing
autostart=true
autorestart=true
startretries=3
user=root
stdout_logfile=/var/www/viax/services/pricing/logs/supervisor.log
stderr_logfile=/var/www/viax/services/pricing/logs/supervisor.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=5MB
stopasgroup=true
killasgroup=true
