[program:viax_dispatch_service]
directory=/var/www/viax/services/dispatch
command=docker compose -f /var/www/viax/services/dispatch/docker-compose.yml up --no-log-prefix
autostart=true
autorestart=true
startretries=3
user=root
stopasgroup=true
killasgroup=true
stdout_logfile=/var/www/viax/services/dispatch/logs/supervisor.log
stderr_logfile=/var/www/viax/services/dispatch/logs/supervisor.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=5MB